name: Convention Commit

on:
  pull_request:

permissions:
  pull-requests: read
  statuses: write

jobs:
  lint:
    name: Validate PR title
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.head_ref, 'release/') }}
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wip: true
